checklist_app/urls.py
from django.urls import path


urlpatterns = [
        
]

todo_app/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.index, name='home'),
    path('create/', views.create, name='create-task'),
    path('update/<int:id>/', views.update_task, name='update-task'),
    path('delete/<int:id>/', views.delete_task, name='delete-task')

]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo_app/', include('todo_app.urls')),
    path('checklist_app/', include('checklist_app.urls'))

]

checklist_app/models.py
from django.db import models
from django.contrib.auth.models import User


class List(models.Model):

    title = models.CharField(max_length=200)
    owners = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_list')
    users = models.ManyToManyField(User, related_name='shared_list')

    def __str__(self) -> str:
        return self.title
    
    def add_user_to_list(self, user):

        self.users.add(user)        

    def remove_user_from_list(self, user):

        self.users.remove(user)


class ListItem(models.Model):

    checklist = models.ForeignKey(List, on_delete=models.CASCADE, related_name='item')
    title = models.CharField(max_length=200)
    status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title

todo_app/models.py
from django.db import models
# Create your models here.

class TaskManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_delete=False)


class Task(models.Model):
    PRIORITY = [
        (0, "Null"),
        (1, "High"),
        (2, "Medium"),
        (3, "Low")
    ]
    COMPLETION_CHOICES = [
        (True, "Completed"),
        (False, "Incomplete")
    ]

    title = models.CharField(max_length=50)
    description = models.TextField()
    priority = models.IntegerField(choices=PRIORITY, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(choices=COMPLETION_CHOICES, default=False)
    deadline = models.DateTimeField(blank=True, null=True)
    is_delete = models.BooleanField(default=False)

    objects = TaskManager()
    admin_objects = models.Manager()    

    def __str__(self):

        return f'{self.title}'

    class Meta:
        verbose_name = 'Task'
        ordering = ['status', 'priority', 'created_at']

todo_app/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description', 'priority', 'deadline']

    widgets = {
        'deadline' : forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    }

checklist_app/views.py
from django.shortcuts import render

# Create your views here.

todo_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from .models import Task
from django.db.models import F
from .forms import TaskForm

# Create your views here.


def index(request):

    queryset = Task.objects.all()

    context = {'queryset': queryset}

    return render(request, 'todo_app/home.html', context)

def create(request):

    if request.method == 'POST':
    
        form = TaskForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect(reverse('home'))

    form = TaskForm()

    return render(request, 'todo_app/create.html', {"form" : form})

def view_tasks(request, id):

    queryset = Task.objects.get(id=id)

    context = {'queryset': queryset}

    return render(request, 'todo_app/view_tasks.html', context)

def update_task(request, id):
    if request.method == 'POST':

        task = Task.objects.get(id=id)
        
        task.status = True  # Toggle the status
        task.save()

    return redirect(reverse('home'))

def delete_task(request, id):
    
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.is_delete = True
        print(task.is_delete)
        task.save()    

    return redirect('home')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        <a class="nav-link" href="{% url 'create-task' %}">Create New Task</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous">
    </script>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('input[type="checkbox"]').change(function () {
                $(this).closest('form').submit();
            });
        });
    </script>
    
</body>

</html>

templates/todo_app/create.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create New Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>

    <div class="container mt-3 col-md-4 card p-3 shadow-lg">
        <div class="container col-md-5">
            <h4>Create New Task</h4>
        </div>
        <br>

        <form method="post" class="form-control card p-3">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label class="form-label">
                        {{ field.label_tag }}
                    </label>
                    
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

templates/todo_app/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock %}

{% block content %}

<div class="container p-3 col-md-4 mt-1">
  <h1>
    Welcome to Easy Todo List App.
  </h1>
</div>
<br>
<br>
{% if queryset %}
<div class="container card col-md-6 shadow-lg">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Priority</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for query in queryset %}
      <tr {% if query.status %} class="table-light" {% endif %}>
        <th scope="row">{{ forloop.counter }}</th>
        <td class="fw-bold">{{ query.title }}</td>
        <td>{{query.description}}</td>
        <td class="fw-bold">{{ query.get_priority_display }}</td>
        <td>
          <form method="post" action="{% url 'update-task' query.id %}">
            {% csrf_token %}
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" role="switch" name="status" {% if query.status %} checked
                {% endif %} onchange="this.form.submit();">
              <label class="form-check-label">{{ query.get_status_display }}</label>
            </div>
          </form>
        </td>
        {% if query.status%}
        <td>
          <form method="post" action="{% url 'delete-task' query.id %}">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-primary btn-danger">
          </form>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<div class="container card col-md-4 p-5 shadow-lg">
  <div class="card-body text-center">
    <h1>No Task Available!</h1>
    <h3>Create New Task</h3>
    <br>
    <a href="{% url 'create-task' %}" class="btn btn-primary">Create</a>
  </div>
</div>
{% endif %}
{% endblock %}

templates/todo_app/view_tasks.html
{% extends 'base.html' %}

{% block content %}

<div class="container p-3">
<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{queryset.title}}</h5>
      <p class="card-text"> {{ queryset.description }} </p>
      <h6>{{ queryset.priority }}</h6>
      <h6>{{ queryset.status }}</h6>
      
    </div>
  </div>
</div>
{% endblock %}

todo_app/templates/todo_app/create.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create New Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>

    <div class="container mt-3 col-md-4 card p-3 shadow-lg">
        <div class="container col-md-5">
            <h4>Create New Task</h4>
        </div>
        <br>

        <form method="post">
            {% csrf_token %}
            
            {{ form.as_p }}



            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>